PresentationLayer/Controllers/CategoryController.cs
using AutoMapper;
using BusinessLayer.Services;
using DataLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly CategoryService categoryService;
        private readonly ILogger<CategoryController> Log;
        private readonly IMapper _Mapper;

        public CategoryController(ILogger<CategoryController> log, CategoryService rep, IMapper mapper)
        {
            categoryService = rep;
            _Mapper = mapper;
            Log = log;
        }
        public bool CheckExistName(string Name) => categoryService.CheckExistName(Name);
        [HttpGet]
        public async Task<IActionResult> Get()=> 
            View("Categories", new CategoryPageModel() { Categories = await categoryService.GetAll() }) ;
        

        [HttpGet]
        public async Task<IActionResult> Delete(long id) {
            categoryService.Delete(id);
            return RedirectToAction("Get"); 
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(CategoryPageModel model)
        {
            if (ModelState.IsValid)
            {
                if (CheckExistName(model.EditModel.Name))
                {
                    TempData["Error"]="Категория с таким названием уже существует";
                    return RedirectToAction("Get");
                }
                var entity = _Mapper.Map<Category>(model.EditModel);
                entity.UserId = UserContext.UserId;
                await categoryService.Add(entity);
            }
            return RedirectToAction("Get");
        }


    }
}

PresentationLayer/Controllers/SettingController.cs
using BusinessLayer.Services;
using DataLayer;
using DataLayer.Models;
using DataLayer.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class SettingController : Controller
    {
        private readonly SettingsService _settingsService;
        private readonly IAccountRepository _accountRepository;
        public EmailSenderService _sender;

        public SettingController(SettingsService service,EmailSenderService sender ,IAccountRepository accountRepository) {
            _settingsService = service;
            _accountRepository = accountRepository;
            _sender = sender;
            
        }
        public async Task<IActionResult> Get(SettingsViewModel setting)
            {
            var model = new SettingsViewModel()
            {
                Url = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}",
                settings = setting.settings,
                Accounts =await _accountRepository.GetAll()
            };
            
            return View("Settings", model);
        }
   

        [HttpPost]
        public async Task<IActionResult> Put(Settings settings) {
            var _newSettings = await _settingsService.Update(settings); 
            return RedirectToAction("Get");
        }

    }
}

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>@ViewData["Title"]</title>
    <partial name="_metaPartial.cshtml" />
    <partial name="_linkPartial.cshtml" />
    <partial name="_scriptsPartial.cshtml" />
</head>
<body>
    <div class="row" >
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
            <div class="container">
                <a class="navbar-brand HeadText my-nav-brand"asp-action="Index" asp-controller="Home">HomeAccounting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-label="Toggle navigation" aria-expanded="true" aria-controls="navbarContent">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav ">
                        <li class="nav-item my-nav-item">
                            <a asp-controller="Transaction" asp-action="Get" class="nav-link my-nav-link">Транзакции</a>
                        </li>
                        <li class="nav-item my-nav-item dropdown">
                            <a href="" class="nav-link my-nav-link  dropdown-toggle" data-bs-toggle="dropdown">Счета</a>
                            <ul class="dropdown-menu ">

                                <li class="link">
                                    <a asp-controller="Account" asp-action="Get" class="link"> 
                                        <img src="/images/allcard.png" alt="" width="30" height="30" />
                                         <span class="link">Мои счета</span>
                                    </a>
                                    
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li class="link">
                                    <a asp-controller="Account" asp-action="EditPage" class="link">
                                    <img src="/images/addcard.png" alt="" width="30" height="30" />

                                    <span class = "link">Создать счет</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item my-nav-item">
                            <a asp-controller="Category" asp-action="Get" class="nav-link my-nav-link">Категории</a>
                        </li>
                        <li class="nav-item my-nav-item">
                            <a asp-action="Statistic" asp-controller="StatisticPage" class="nav-link my-nav-link">Статистика</a>
                        </li>
                        <li class="nav-item my-nav-item dropdown">
                            <a href="" class="nav-link my-nav-link  dropdown-toggle" data-bs-toggle="dropdown">Разработчик</a>
                            <ul class="dropdown-menu ">
                                <li class="link">                                    
                                    <a href="https://vk.com/mikov2003" class="linkUsualText">
                                        <img src="/images/vk.png" class="" width="30" height="30" />
                                        <span class="linkUsualText">Vcontacte</span>
                                    </a>
                                </li>
                                <li class="link">
                                    <a href="https://t.me/Artem6115" class="linkUsualText">
                                        <img src="/images/tg.png" class="" width="30" height="30" />
                                        <span class="linkUsualText">Telegram</span>
                                        
                                     </a>
                                </li>
                                <li class="link">
                                    <a href="https://github.com/artem6115/HomeAccounting" class="linkUsualText">
                                        <img src="/images/git.png" class="" width="30" height="30" />
                                        <span class="linkUsualText">GitHub</span>     
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item my-nav-item">
                            <a asp-action="Get" asp-controller="Setting" class="nav-link my-nav-link">Настройки</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ms-auto ">
                        <li class="nav-item my-nav-item ">
                            <a href="" class="nav-link my-nav-link  ">@UserContext.UserName</a>
                        </li>
                        <li class="nav-item  ">
                            <a href=""><img src="/images/nologin.png" class="mt-1" width="35" height="35" /></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    @RenderBody()
</body>
<!-- Footer -->
</html>

PresentationLayer/Views/Shared/_footerPartial.cshtml
<div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="https://vk.com/mikov2003" role="button">
            <img src="/images/vk.png" />
        </a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="https://t.me/Artem6115 role="button">
            <img src="/images/tg.png" />
        </a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/artem6115/HomeAccounting" role="button">
            <img src="/images/git.png" />
        </a>


    </section>

    <section class="mb-4">
        <div class="row ">
            <div class="col-6 mx-auto ">
                <p>

                    Данный сервис предназначен для бесплатного пользования.
                    Записывайте полную информацию об операциях.
                    Изучайте полученую статистику. Редактируйте и экспортируйте данные.



                </p>
                Используйте Telegram-бота  -
                <button class="btn btn-info">AccountingBot</button>
            </div>
        </div>
    </section>

    <section class="mb-4">
    </section>

</div>
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright: Миков А.А.
</div>

PresentationLayer/Views/Shared/_linkPartial.cshtml
<link asp-append-version=true rel="shortcut icon" href="~/images/icon.png">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" asp-append-version=true href ="~/css/site.css" asp-append-version="true" />

PresentationLayer/Views/Shared/_metaPartial.cshtml
<meta charset="utf-8" />
<meta name="author" content="Миков Артём Андреевич">
<meta name="copyright" content="Все права принадлежат Микову Артёму">
<meta http-equiv="content-type" content="text/html;">
<meta name="keywords" content="Домашняя онлайн бухгалтерия,учет домашних расходов,бухгалтерия,учет,учёт,транзакции,домашняя,онлайн,бесплатно,бесплатная,домашних,расходов,расходы,доходы,доходов">
<meta name="description" content="Домашняя онлайн бухгалтерия">

PresentationLayer/Views/Shared/_scriptsPartial.cshtml
<!--Bootstrap-->
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<!--My scripr and Chart librory-->
<script asp-append-version="true" src="~/js/Ajax.js"></script>
<script asp-append-version="true"  src="~/js/ChartMethods.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
     
<!--Validation-->
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>