PresentationLayer/Models/TransactionViewModel.cs
using DataLayer.Entities;
using DataLayer.Models;



namespace PresentationLayer.Models
{
    public class TransactionViewModel
    {
        public List<Account> Accounts { get; set; }
        public List<Category> Categories { get; set; }
        public Filter Filter { get; set; }
        public List<Transaction> Transactions { get; set; }
        public int NumberOfLastPage { get; set; }


        //Адресс сервера, схема + адрес
        public string Url { get; set; }

        //Сумма всех транзакций
        public string Sum { get; set; }
        
    }
}

PresentationLayer/Controllers/CategoryController.cs
using AutoMapper;
using BusinessLayer.Services;
using DataLayer;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly CategoryService categoryService;
        private readonly ILogger<CategoryController> Log;
        private readonly IMapper _Mapper;

        public CategoryController(ILogger<CategoryController> log, CategoryService rep, IMapper mapper)
        {
            categoryService = rep;
            _Mapper = mapper;
            Log = log;
        }
        public bool CheckExistName(string Name) => categoryService.CheckExistName(Name);
        [HttpGet]
        public async Task<IActionResult> Get()=> 
            View("Categories", new CategoryPageModel() { Categories = await categoryService.GetAll() }) ;
        

        [HttpGet]
        public async Task<IActionResult> Delete(long id) {
            categoryService.Delete(id);
            return RedirectToAction("Get"); 
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Add(CategoryPageModel model)
        {
            if (ModelState.IsValid)
            {
                if (CheckExistName(model.EditModel.Name))
                {
                    TempData["Error"]="Категория с таким названием уже существует";
                    return RedirectToAction("Get");
                }
                var entity = _Mapper.Map<Category>(model.EditModel);
                entity.UserId = UserContext.UserId;
                await categoryService.Add(entity);
            }
            return RedirectToAction("Get");
        }


    }
}

PresentationLayer/Controllers/TransactionController.cs
using AutoMapper;
using BusinessLayer.Services;
using DataLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using Microsoft.AspNetCore.Http.Extensions;
using DataLayer.Repositories;
using DataLayer.Models;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using static System.Runtime.InteropServices.JavaScript.JSType;
using DataLayer.Repository;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly TransactionService _transactionService;
        private readonly IInventoryRepository _inventoryRepository;
        private readonly IAccountRepository _accountRepository;
        private readonly ICategoryRepository _categoryRepository;

        private readonly ILogger<TransactionController> _log;
        private readonly IMapper _mapper;

        public TransactionController(ILogger<TransactionController> log, TransactionService trs, 
            IInventoryRepository inventoryRepository, IMapper mapper,
            IAccountRepository accountRepository, ICategoryRepository categoryRepository)
        {
            _transactionService = trs;
            _mapper = mapper;
            _log = log;
            _inventoryRepository = inventoryRepository;
            _accountRepository = accountRepository;
            _categoryRepository = categoryRepository;
        }
        [HttpGet]

        public async Task<IActionResult> Get(Filter filter) {
            var QueryExecuted = await _transactionService.GetTransactionsWithFilterByPages(filter);
            TransactionViewModel model = new TransactionViewModel() {
                Accounts = await _accountRepository.GetAll(),
                Categories = await _categoryRepository.GetAll(),
                Filter = filter,
                Transactions = QueryExecuted.Transactions,
                NumberOfLastPage = QueryExecuted.PageCount,
                Url = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}",
                Sum = _transactionService.ParseValue(QueryExecuted.Sum)

            };
            HttpContext.Session.Set("url",Encoding.UTF8.GetBytes(HttpContext.Request.GetDisplayUrl()));
            return View("Transactions", model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteByFilter( Filter filter)
        {
            await _transactionService.DeleteByFilter(filter);
            return RedirectToAction("Get");
        }

        [HttpGet]
        public async Task<IActionResult> EditPage(long? id)
        {
            TransactionEditPageModel model = new();
            if (id.HasValue)
            {
                var entity =await _transactionService.Get(id.Value);
                model.EditModel = _mapper.Map<TransactionEditModel>(entity);
            }
            else
                model.EditModel = new TransactionEditModel() {Date = CurrentDate()};
            

            model.Accounts = await _accountRepository.GetAll();
            model.Categories = await _categoryRepository.GetAll();
            return View("TransactionEdit", model);
        }

        private DateTime CurrentDate()
        {
            var date = DateTime.Now;
            return new DateTime(date.Year, date.Month, date.Day, date.Hour, date.Minute, 0);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(TransactionEditPageModel model)
        {
            if (ModelState.IsValid)
            {
                if (!model.EditModel.Id.HasValue)
                {
                    await _transactionService.Add(_mapper.Map<Transaction>(model.EditModel));
                    TempData["Message"] = "Транзакция добавлена";
                }
                else
                {
                    await _transactionService.Edit(_mapper.Map<Transaction>(model.EditModel));
                    TempData["Message"] = "Транзакция отредактирована";
                }
                TempData["MessageStyle"] = "alert-success";
                TempData["MessageColor"] = "green";
                HttpContext.Session.TryGetValue("url", out var bytes_url);
                if (bytes_url != null)
                {
                    var url = Encoding.UTF8.GetString(bytes_url);
                    return Redirect(url);
                }
                return RedirectToAction("Get");
            }
            return RedirectToAction("EditPage",model.EditModel.Id);
        }

        public async Task<IActionResult> Delete(long id)
        {
            _transactionService.Delete(id);
            TempData["Message"] = "Транзакция удалена";
            TempData["MessageStyle"] = "alert-danger";
            TempData["MessageColor"] = "red";
            HttpContext.Session.TryGetValue("url", out var bytes_url);
            if (bytes_url != null)
            {
                var url = Encoding.UTF8.GetString(bytes_url);
                return Redirect(url);
            }
            return RedirectToAction("Get");

        }




    }
}

PresentationLayer/Views/Transaction/TransactionEdit.cshtml
@model TransactionEditPageModel
@{
    ViewData["Title"] = "Создание/редактирование транзакции";
}
<script>
    function back(){

    }
</script>
<div class="row justify-content-center ">
    <div class="col-lg-8 col-11">
        <form method="post" asp-asp-controller="Transaction" asp-action="Edit">
            <div class="row justify-content-center mt-4">
                <h1>@(Model is not null?"Редактирование транзакции":"Добавление транзакции")</h1>
                <div class="col-lg-6 col-12 ">

                    <input asp-for=@Model.EditModel.Id hidden="hidden"/>
                    <label class="form-label">Выберите счет</label>
                    <select asp-for=@Model.EditModel.AccountId class="form-select">
                        @foreach (var item in Model.Accounts)
                        {
                            <option value=@item.Id>@item.Name</option>
                        }
                
                    </select>
                    <a asp-controller="Account" asp-action="EditPage" class="link"><span asp-validation-for=@Model.EditModel.AccountId class="validationError"></span></a>


                    <br />
                    <label class="form-label">Укажите величену</label>
                    
                  
                    <div class="input-group mb-3">
                        <span class="input-group-text">Доход</span>
                        <div class="input-group-text">
                            <input type="checkbox" class="form-check-input" asp-for=@Model.EditModel.IsIncome />
                        </div>
                        <input class="form-control" asp-for=@Model.EditModel.Value />
                        
                    </div>
                    <span asp-validation-for=@Model.EditModel.Value class="validationError"></span>
                    

                </div>
                <div class="col-lg-6 col-12">
                    <label class="form-label">Выберите категорию*</label>
                    <a asp-action="Get" asp-controller="Category" class="btn btn-success m-2">Добавить категорию</a>
                    <select asp-for=@Model.EditModel.CategoryId class="form-select">
                        <option value="">-</option>

                        @foreach (var item in Model.Categories)
                        {
                            <option value=@item.Id>@item.Name</option>
                        }
                    </select>

                    <br />
                    <label class="form-label ">Укажите дату</label>
                    <input asp-for=@Model.EditModel.Date class="form-control" />
                    <span asp-validation-for=@Model.EditModel.Date class="validationError"></span>
                    
                    <br />
                    <label class="form-label">Напишите коментарий*</label>
                    <input asp-for=@Model.EditModel.Comment class="form-control" />
                </div>

            </div>
            <div class="row justify-content-center ">
                <div class="col-lg-3 mt-5">
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <button onclick="window.history.go(-1);return false" class="btn btn-secondary">Отменить</button>

                </div>
            </div>
        </form>

    </div>
</div>

PresentationLayer/Views/Transaction/Transactions.cshtml
@model TransactionViewModel
@{

    ViewData["Title"] = "Транзакции";
    string? message = TempData["Message"]?.ToString();
    string? messageStyle = TempData["MessageStyle"]?.ToString()!;
}
<script>
    //Скрытие меню
    function MoveToolBar (){
        document.getElementById("ToolBar").classList.toggle("ActiveBar");
    }
    //Запрос на удаление записи
    function DeleteNote(id) {
        let urlToDelete = "delete/" + id;
        if (confirm("Вы уверены, что хотите удалить транзакцию?")) {
            window.location.replace(urlToDelete);
        }
    }
    //Удаление всех выборки
    function DeleteAllByFilter() {
        if (confirm("Вы уверены, что хотите удалить данные транзакции?")) {
            let form = document.getElementById("FilterForm");

            form.action = "@(Model.Url)/Transaction/DeleteByFilter";
            form.submit();
        }
    }
    function GetExcel() {
        let form = document.getElementById("FilterForm");
        form.action = "@(Model.Url)/api/File/excel";
        form.submit();
    }
    function GetWord() {
        let form = document.getElementById("FilterForm");
        form.action = "@(Model.Url)/api/File/word";
        form.submit();
    }
    function GetFilter() {
        let form = document.getElementById("FilterForm");

        form.action = "@(Model.Url)/Transaction/Get";
        form.submit();
    }
    function MovePage(number){
        let form = document.getElementById("FilterForm");
        document.getElementById("PageNumber").value = number;
        form.action = "@(Model.Url)/Transaction/Get";
        form.submit();
    }

</script>

<div class="ToolBar" id="ToolBar">  
    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="col-12">
                <form method="get" id="FilterForm">
                    <input id="PageNumber" asp-for=@Model.Filter.PageNumber type="hidden" hidden value="0"/>
                    <div class="row justify-content-center mt-1">
                        <div class="col-2">
            
                            <select asp-for=@Model.Filter.AccountId class="form-select">
                                <option class="active" value="">Все счета</option>
                                @foreach (var item in Model.Accounts)
                                {
                                    <option value=@item.Id>@item.Name</option>
                                }
                                
                            </select>
                        </div>
                        <div class="col-2">


                            <div class="input-group">

                                <input asp-for=@Model.Filter.PageNumber value="0" hidden="hidden" />
                                <input asp-for=@Model.Filter.Value class="form-control valueInput" placeholder="(>,<,=) Стоимость" />
                                <span class="input-group-text">₽</span>


                            </div>
                         </div>
                        <div class="col-2"><input asp-for=@Model.Filter.Date class="form-control" type="date" placeholder="Дата" /></div>
                        <div class="col-3 ">
                            <input asp-for="@Model.Filter.StringToFind" class="form-control" placeholder="Что искать..." />
                        </div>
                        <div class="col-1 mt-1">
                            <p data-tooltip="Применить фильтр">
                            <button class="btn" onclick="GetFilter()"><img src="/images/filtr.png" /></button>
                            </p>
                        </div>
                    </div>
                    <div class="row justify-content-center mt-3">
                        <div class="col-2">
                            <select asp-for=@Model.Filter.CategoryId class="form-select" data-mdb-filter="true">
                                <option class="active" value="">Без категорий</option>

                                @foreach (Category item in Model.Categories)
                                {
                                    <option value=@item.Id>@item.Name</option>
                                }
                            </select>
                        </div>
                        <div class="col-2">
                            <select  class="form-select" asp-for=@Model.Filter.TypeTransaction>
                                <option value="0">Доходы/расходы</option>
                                <option value="1">Доходы</option>
                                <option value="-1">Расходы</option>
                            </select>
                        </div>
                        <div class="col-2">
                            <select class="form-select" asp-for=@Model.Filter.PropetryForSorting>
                                <option value="">Без сортировки</option>
                                <option value="date">Сортировка по дате</option>
                                <option value="value">Сортировка по стоимости</option>
                                <option value="category">Сортировка по категории</option>
                                <option value="account">Сортировка по счету</option>
                            </select>
                        </div>
                        <div class="col-3">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <h5 style="color:white;" class="input-grop-text">В порядке возростания </h5>
                                </div>
                                <input type="checkbox" asp-for=@Model.Filter.IsForward class="form-check-input m-lg-2 mt-2" />
                            </div>
                        </div>
                        <div class="col-1">
                            <p data-tooltip="Удалить фильтр">
                            <a class = "btn ml-1" asp-controller="Transaction" asp-action="Get"><img src="/images/NoFilter.png" /></a>
                            </p>
                        </div>

                        
                    </div>

                </form>
            </div>
        </nav>
    </div>
    <div class="menuButton">
       <button class="btn" onclick="MoveToolBar()">
           <img asp-append-version=true src="/images/filtrMune.png" width="50px" height="50px"/>
       </button>
    </div>
</div>

@if (message is not null && message != "")
{
    <div class="alert @messageStyle mt-3 mb-3 text-center" style="z-index:0;">@message</div>
}
<div class="work-panel">
    <div style="width:55px;height:55px" class="m-2">
        <p data-tooltip="Добавить транзакцию">
        <a  asp-controller="Transaction" asp-action="EditPage"><img  width="50px" height="50px" src="/images/addTransaction.png" /></a>
        </p>
    </div>
    <div style="width:55px;height:55px" class="m-2">

        <p data-tooltip="Удалить все транзакци в выборке">
            <button style="padding:0;" class="btn" onclick="DeleteAllByFilter()"><img width="50px" height="50px" src="/images/delete_all_by_filter.png" /></button>
        </p>

    </div>
    <div style="width:55px;height:55px" class="m-2">
        <p data-tooltip="Скачать Excel документ">
        @* <a href="@(Model.Url)/api/File/excel?@(ReflectionServies.GetQueryString(Model.Filter))"><img width="50px" height="50px" src="/images/excel.png" /></a> *@
        <button class="btn p-0" onclick="GetExcel()"><img width="50px" height="50px" src="/images/excel.png" /></button>
        <p/>

    </div>
    <div style="width:55px;height:55px" class="m-2">
        <p data-tooltip="Скачать Word документ">
            <button class="btn p-0" onclick="GetWord()"><img width="50px" height="50px" src="/images/word.png" /></button>
       </p>

    </div>
</div>
<div class="container mt-4">
    <div class="row mt-3 mb-3  justify-content-center">
        <div class="col-6">
            <div class="row" style="display:inline;">
                <h4 style="display:inline;">Сумма = </h4><h4 style="color:@(Model.Sum[0]!='-'?"green":"red");display:inline;">@Model.Sum</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table id="table" class=" table table-striped table-bordered  table-hover" width="100%">
                <thead>
                    <tr>
                        <th>
                            <p>Счет</p>
                        </th>

                        <th>
                            <p> Категория</p>
                        </th>
                        <th>
                            <p> Стоимость</p>
                        </th>
                        <th><p> Описание</p></th>
                        <th>
                            <p> Дата</p>
                        </th>
                        <th colspan="2">
                            <p>Редактирование</p>
                        </th>
                    </tr>
                </thead>
                <tbody> 
                    @foreach(Transaction item in Model.Transactions){
                        <tr>
                            <td>@item.Account.Name</td>
                            <td>@item.Category?.Name</td>
                            <td style="color:@(item.IsIncome?"green":"red")">@item.Value</td>
                            <td>@item.Comment</td>
                            <td>@item.Date.ToString()</td>
                            <td class="td-edit">
                                <a class="btn" asp-controller="Transaction" asp-action="EditPage" asp-route-Id=@item.Id><img src="/images/editnote.png" /></a>
                            </td>
                            <td class="td-edit">
                                <button class="btn" onclick="DeleteNote(@item.Id)"><img src="/images/delete.png" /></button>
                            </td>
                        </tr>
                    }
                </tbody>
                @if (Model.Transactions.Count > 10)
                {
                    <tfoot>
                        <tr>
                            <th>Счет</th>
                            <th>Категория</th>
                            <th>Стоимость</th>
                            <th>Описание</th>
                            <th>Дата</th>
                        </tr>
                    </tfoot>
                }
            </table>
        </div>
    </div>
</div>
@if (Model.NumberOfLastPage>1)
{
    <div class="row justify-content-center mb-4">
        <div class="col-6 text-center">
            @if (Model.Filter.PageNumber != 0)
            {
                <button class="btn btn-secondary" onclick="MovePage(0)">Первая страница</button>
                <button class="p-0 btn" onclick="MovePage(@(Model.Filter.PageNumber-1))"><img src="/images/back.png" /></button>
            }
            <span>@(Model.Filter.PageNumber + 1)</span>
            @if (Model.Filter.PageNumber != Model.NumberOfLastPage - 1)
            {
                <button class="p-0 btn" onclick="MovePage(@(Model.Filter.PageNumber+1))"><img src="/images/next.png" /></button>
                <button class="btn btn-secondary" onclick="MovePage(@(Model.NumberOfLastPage-1))">Последняя страница - @(Model.NumberOfLastPage)</button>
            } 
        </div>
    </div>
}