PresentationLayer/Controllers/UserManagerController.cs
using BusinessLayer.Services;
using DataLayer;
using DataLayer.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.Models;
using System.ComponentModel.DataAnnotations;

namespace PresentationLayer.Controllers
{
    public class UserManagerController : Controller
    {
        private readonly EmailSenderService _emailService;
        private readonly ILogger<UserManagerController> _logger;
        private readonly IUserRepository _userRepository;


        public UserManagerController(IUserRepository userRepository,EmailSenderService sender , ILogger<UserManagerController> logger)
        {
            _emailService = sender;
            _logger = logger;
            _userRepository = userRepository;
        }

       
        public async Task<IActionResult> ResetPassword(ResetPasswordModel model)
        {
            if(model.Email == null) return View("InputEmail", model);

            if ( await _userRepository.UserExist(model.Email)) {
                if (model.Code == null)
                {
                    string code = await _userRepository.AddSecretCode(model.Email);
                    string url = $"https://localhost:7177/UserManager/ResetPassword?email={model.Email}&code={code}";
                    _emailService.Send(model.Email,$"Код востановления пароля: {code}\nТак же вы можете сменить пароль перейдя по ссылке:\n{url}","Востановление пароля");
                    return View("VerifiCode", model);
                }
                if(await _userRepository.VerifiCode(model.Email,model.Code)) { 

                    if(model.Password == null || !ModelState.IsValid)
                    {
                        return View("ResetPassword", model);
                    }
                    _userRepository.ResetPassword(model.Email, model.Password);
                    _logger.LogInformation("Password reset");

                    return RedirectToAction("Index","Home");
                }
                else
                {
                    TempData["error"] = "Код не верный";
                    return View("VerifiCode", model);
                }
            }
            TempData["error"] = "Учетная запись на данную почту отсутвует";
            return View("InputEmail", model);
        }
        [Authorize]
        public async Task<IActionResult> DeleteUser([FromServices] UserManager<ApplicationUser> userManager, [FromServices] SignInManager<ApplicationUser> signInManager)
        {
            var user =await userManager.GetUserAsync(User);
            signInManager.SignOutAsync();
            userManager.DeleteAsync(user);
            return RedirectToAction("Index", "Home");
        }

    }
}

PresentationLayer/Views/UserManager/InputEmail.cshtml
@{
    string error = TempData["error"]?.ToString();
    Layout = "/Areas/Identity/Pages/_layout.cshtml";
    ViewData["Title"] = "Востоновление пароля";
}
@model ResetPasswordModel
<div calss="row justify-content-center">
    <div class="col-md-4 position-absolute top-50 start-50 translate-middle LoginWindow">
        <form method="post" asp-controller="UserManager" asp-action="ResetPassword">
            <div class="row justify-content-center mt-3 mb-3">
                <div class="col-9">
                    <h6 class="form-label">Введите почту к которой привязан аккаунт</h6>
                    <input class="form-control" asp-for="Email" />
                    <span asp-validation-for="Email" class="error_text"></span>
                    <span class="error_text">@error</span>
                    <br />
                    <button type="submit" class="btn btn-success mt-2">Далее</button>
                </div>
            </div>
        </form>
    </div>
</div>

PresentationLayer/Views/UserManager/ResetPassword.cshtml
@{
    ViewData["Title"] = "Востоновление пароля";
    string error = TempData["error"]?.ToString();
    Layout = "/Areas/Identity/Pages/_layout.cshtml";

}
@model ResetPasswordModel

<div calss="row justify-content-center">
    <div class="col-md-4 position-absolute top-50 start-50 translate-middle LoginWindow">
        <form method="post" asp-controller="UserManager" asp-action="ResetPassword">
            <div class="row justify-content-center mt-3 mb-3">
                <div class="col-9">
                    <input class="form-control" asp-for="Email" hidden type="hidden" />
                    <input class="form-control" asp-for="Code" hidden type="hidden" />

                    <h6 class="form-label">Введите новый пароль</h6>
                    <input class="form-control" asp-for="Password" />
                    <span asp-validation-for="Password" class="error_text"></span>
                    <span class="error_text">@error</span>
                    <br />
                    <button type="submit" class="btn btn-success mt-2">Сменить пароль</button>
                </div>
            </div>
        </form>
    </div>
</div>

PresentationLayer/Views/UserManager/VerifiCode.cshtml
@{
    ViewData["Title"] = "Востоновление пароля";
    string error = TempData["error"]?.ToString();
    Layout = "/Areas/Identity/Pages/_layout.cshtml";

}
@model ResetPasswordModel
<div calss="row justify-content-center">
    <div class="col-md-4 position-absolute top-50 start-50 translate-middle LoginWindow">
        <form method="post" asp-controller="UserManager" asp-action="ResetPassword">
            <div class="row justify-content-center mt-3 mb-3">
                <div class="col-9">
                    <input class="form-control" asp-for="Email" hidden type="hidden" />
                    <h6 class="form-label">Введите код отправленый на почту</h6>
                    <input class="form-control" asp-for="Code" />
                    <span asp-validation-for="Code" class="error_text"></span>
                    <span class="error_text">@error</span>
                    <br />
                    <button type="submit" class="btn btn-success mt-2">Отправить/Запросить код</button>
                </div>
            </div>
        </form>
    </div>
</div>