PresentationLayer/Controllers/StatisticController.cs
using Microsoft.AspNetCore.Mvc;
using DataLayer.Models;
using BusinessLayer.Services;
using DataLayer.Repositories;
using Microsoft.AspNetCore.Authorization;

namespace PresentationLayer.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]

    public class StatisticController : ControllerBase
    {
        private readonly IStatisticRepository _statisticRepository;
        private readonly ILogger<StatisticController> _logger;
        public StatisticController(IStatisticRepository statisticService, ILogger<StatisticController> log)
        {
            _statisticRepository = statisticService;
            _logger = log;
           
        }

        [HttpGet]
        [Route("category")]

        //Example query -
        //https://localhost:7177/api/statistic/category   - empty
        //https://localhost:7177/api/statistic/category?allaccounts=true
        //https://localhost:7177/api/statistic/category?allaccounts=true&alltime=true&year=2023&month=11
        public async Task<IEnumerable<StatisticData>> Category([FromQuery] StatisticFilter filter)
        {
            //filter = new StatisticFilter()
            //{
            //    AllAccounts = true,
            //    AccountId=72,
            //    AllTime = true,
            //    TypeTransaction = DataLayer.Enum.TypeTransaction.Expense,
            //    Month=11,
            //    Year=2023,
            //    TimeGroup=DataLayer.Enum.TimeGroup.Day

            //};
            _logger.LogDebug("Get запрос к api контроллеру, метод расчета категорий");
            return await _statisticRepository.BuildCategoriesStatistic(filter);
        }

        [HttpGet]
        [Route("transaction")]
        public async Task<IEnumerable<StatisticData>> Transaction([FromQuery] StatisticFilter filter)
        {
            _logger.LogDebug("Get запрос к api контроллеру, метод расчета транзакций");
            return await _statisticRepository.BuildTransactionStatistic(filter);
        }

        [HttpGet]
        [Route("balance")]
        public async Task<IEnumerable<StatisticData>> Balance([FromQuery] StatisticFilter filter)
        {
            _logger.LogDebug("Get запрос к api контроллеру, метод расчета баланса");
            return await _statisticRepository.BuildBalanceStatistic(filter);
        }

    }
}

PresentationLayer/Controllers/StatisticPageController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PresentationLayer.Controllers
{
    [Authorize]

    public class StatisticPageController : Controller
    {
        public IActionResult Statistic()
        {
            ViewData["url"] = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/api/statistic";
            return View(new StatisticFilter() { Month = DateTime.Now.Month, Year = DateTime.Now.Year });
        }

    }
}

PresentationLayer/Views/StatisticPage/Statistic.cshtml
@model StatisticFilter
@inject AccountService _accountService
@{
    ViewData["Title"] = "Статистика";
    string url = ViewData["url"].ToString();
    var Accounts = _accountService.GetAll().Result ?? new List<Account>(0);
}
<script>
    var CurrentCanvas = "category";
    var IsIncome = false;
    var GroupByMonth = false;
    var DataName = "";
    var Title = "";

    function MoveToolBar() {
        document.getElementById("ToolBar").classList.toggle("ActiveStatisticBar");
    }

    async function Load() {
        var result;
        DataName = "Сумма ";
        Title = "Статистика по категориям";

        if (CurrentCanvas === "category")
            result = await LoadData('@(url)/category?');
        else if (CurrentCanvas === "transaction") {
            result = await LoadData('@(url)/transaction?');
            DataName = (IsIncome===true)? "Доход " : "Расход ";
            Title = "Статистика по транзакциям";

        }
        else {
            result = await LoadData('@(url)/balance?');
            DataName = "Баланс ";
            Title = "Изменения баланса";

        }
        Drow(result);
    }


</script>

<div class="ToolBar" id="ToolBar">
    <div class="row">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="col-12">
                <form class="AjaxForm statisticForm" method="get" asp-controller="Statistic">
                    <div class="row justify-content-center ">
                        <div class="col-2">
                            <label class="form-label">Выберите счёт</label>
                            <select asp-for="AccountId" class="form-select">
                                @foreach (var item in Accounts)
                                {
                                    <option value=@item.Id>@item.Name</option>
                                }
                            </select>
                        </div>
                        <div class="col-2">
                            <label class="form-label">Выберите месяц</label>
                            <select asp-for="Month" class="form-select">
                                <option value="1" >Январь</option>
                                <option value="2">Февраль</option>
                                <option value="3">Март</option>
                                <option value="4">Апрель</option>
                                <option value="5">Май</option>
                                <option value="6">Июнь</option>
                                <option value="7">Июль</option>
                                <option value="8">Август</option>
                                <option value="9">Сентябрь</option>
                                <option value="10">Октябрь</option>
                                <option value="11">Ноябрь</option>
                                <option value="12">Декабрь</option>
                            </select>
                        </div>
                        <div class="col-2">
                            <label class="form-label">Введите год</label>
                            <input asp-for="Year" class="form-control"/>
                        </div>
                        <div class="col-3 mt-5">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <h5 class="input-grop-text" style="color:white;">По всем счетам</h5>
                                </div>
                                <input type="checkbox" asp-for="AllAccounts" class="form-check-input m-lg-2 mt-2" />
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center ">
                        <div class="col-2">
                            <label class="form-label">Выберите тип транзакций</label>
                            <select asp-for="TypeTransaction" class="form-select">
                                <option value="-1">Расход</option>
                                <!--<option value="0" disabled>Расход/Доход</option>-->
                                <option value="1">Доход</option>
                            </select>
                        </div>
                        <div class="col-2">
                            <label class="form-label">Выберите тип группировки</label>
                            <select asp-for="TypeGroup" class="form-select">
                                <option value="0">День</option>
                                <option value="2">Месяц</option>
                            </select>
                        </div>
                        <div class="col-2">
                         
                        </div>

                 

                        <div class="col-3 mt-5">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <h5 class="input-grop-text" style="color:white;">За все время(только для категорий)</h5>
                                </div>
                                <input type="checkbox" asp-for="AllTime" class="form-check-input m-lg-2 mt-2" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </nav>
    </div>
    <div class="menuFilterButton">
        <button class="btn" onclick="MoveToolBar()">
            <img asp-append-version=true src="/images/setting1.png" width="50px" height="50px" />
        </button>
    </div>
</div>

<div class="row mt-3 mb-3 justify-content-center">
    <div class="col-2">
        <button class="btn btn-success"  onclick="Load()">  
             Загрузить данные
            <img class="ml-1" src="~/images/drow.png" />
        </button>
        
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-lg-10 col-12">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button onclick="CurrentCanvas='category'" class="nav-link active" id="Category-tab" data-bs-toggle="tab" data-bs-target="#Category" type="button" role="tab" aria-selected="true">Категории</button>
            </li>
            <li class="nav-item" role="presentation">
                <button onclick="CurrentCanvas='transaction'" class="nav-link" id="Transaction-tab" data-bs-toggle="tab" data-bs-target="#Transaction" type="button" role="tab" aria-selected="false">Транзакции</button>
            </li>
            <li class="nav-item" role="presentation">
                <button  onclick="CurrentCanvas='balance'" class="nav-link" id="Balance-tab" data-bs-toggle="tab" data-bs-target="#Balance" type="button" role="tab" aria-selected="false">Баланс</button>
            </li>
        </ul>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active " id="Category" role="tabpanel" aria-labelledby="Category-tab">
                <div class="row justify-content-center">
                    <div class="col-lg-6 col-10" id="canvas-Div-category">
                        <canvas id="canvas-category">
                        </canvas>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="Transaction" role="tabpanel" aria-labelledby="Transaction-tab">
                <div class="row justify-content-center">
                    <div class="col-lg-10 col-10" id="canvas-Div-transaction">
                        <canvas id="canvas-transaction">
                        </canvas>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="Balance" role="tabpanel" aria-labelledby="Balance-tab">
                <div class="row justify-content-center">
                    <div class="col-lg-10 col-10" id="canvas-Div-balance">
                        <canvas id="canvas-balance">
                        </canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>


 function Drow(json) {
    var cnv = Update();
    var ctx = cnv.getContext('2d');
    let data = GetDateBar(json,GroupByMonth);
    let chartType = "bar";
     if (CurrentCanvas === "category") {
         chartType = 'pie'
         data = GetDatePie(json);

     }
    else if (CurrentCanvas === "balance")
        chartType = 'line'
     data.datasets[0].label = DataName;
    let chart = new Chart(ctx, {
        type:chartType,
        data: data,
        options: {
            layout: {
                padding: {
                    top: 25,
                }
            },
            legend: {
                display: true,
                labels: {
                    padding: 500
                }
            },
            plugins: {
                legend: {
                    position: 'right'
                },
                title: {
                    display: true,
                    text: Title,
                }

            }
        }

    });
}
</script>